name                 'fhuertas-jre_install'
version              '0.0.1'
summary              'Install JRE without package system. This module install any jre version'
source               'https://github.com/yunxao/puppet_manual_jre_install'
project_page         'https://github.com/yunxao/puppet_manual_jre_install'
description          'Install JRE without package system. This module install any jre version'
project_page         'https://github.com/yunxao/puppet_manual_jre_install'
license              'Apache 2.0'
author               'Francisco Huertas Ferrer'


